### ISSUE TITLE
getting outputs  undefined

### ISSUE THREAD

**Issue by binyamhailu** [jackbridger/streampot-ai-video-example#2]
i am getting the follwoing  when i try to get the job status
JobEntity {
  id: 7,
  status: 'completed',
  outputs: undefined,
  logs: undefined,
  created_at: '2024-08-01T12:18:29.430Z'
}

**Comment by jackbridger** [comment]
Could you share a repo or more of your code with me and I'll take a look?

**Comment by binyamhailu** [comment]
it was happening when I was using  the streampot/server:latest docker image but I fixed it  by building a new docker image from the streampot repo server folder source code

**Comment by jackbridger** [comment]
ahhh I see thanks very much, we will update it.
